# See https://github.com/google-github-actions/release-please-action
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build and test
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm build
          pnpm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
        if: github.ref == 'refs/heads/main'
      - name: Publish
        run: |
          pnpm build
          pnpm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
